[package]
name = "rust-ln-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.1"
bitcoin-bech32 = "0.12"
lightning = { version = "0.0.103", features = ["_test_utils"] }
lightning-block-sync = { version = "0.0.103", features = [ "rpc-client" ] }
lightning-invoice = { version = "0.11.0" }
lightning-net-tokio = { version = "0.0.103" }
lightning-persister = { version = "0.0.103" }
lightning-background-processor = { version = "0.0.103" }

base64 = "0.13.0"
bech32 = "0.8"
chrono = "0.4"
futures = "0.3"
hex = "0.3"
#rand = "0.8.4"
rand = "0.4"
serde_json = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.5"
warp = "0.3"
