[package]
name = "rapid-gossip-sync-server"
version = "0.1.0"
edition = "2018"

[dependencies]
bitcoin = "0.28.1"
lightning = { version = "0.0.110" }
lightning-block-sync = { version = "0.0.110", features=["rest-client"] }
lightning-net-tokio = { version = "0.0.110" }
tokio = { version = "1.14.1", features = ["full"] }
tokio-postgres = { version="0.7.5" }

[profile.release]
opt-level = 3
lto = true
panic = "abort"
