[package]
name = "rapid-gossip-sync-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.29"
lightning = { version = "0.0.116-alpha1" }
lightning-block-sync = { version = "0.0.116-alpha1", features=["rest-client"] }
lightning-net-tokio = { version = "0.0.116-alpha1" }
tokio = { version = "1.25", features = ["full"] }
tokio-postgres = { version="=0.7.5" }
futures = "0.3"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
